export const TextNameColorTernary = (mainType: string) => {
  const style =
    mainType === 'grass'
      ? 'text-background-type-grass'
      : mainType === 'dark'
      ? 'text-background-type-dark'
      : mainType === 'dragon'
      ? 'text-background-type-dragon'
      : mainType === 'fairy'
      ? 'text-background-type-fairy'
      : mainType === 'fighting'
      ? 'text-background-type-fighting'
      : mainType === 'fire'
      ? 'text-background-type-fire'
      : mainType === 'ghost'
      ? 'text-background-type-ghost'
      : mainType === 'bug'
      ? 'text-background-type-bug'
      : mainType === 'ground'
      ? 'text-background-type-ground'
      : mainType === 'normal'
      ? 'text-background-type-normal'
      : mainType === 'poison'
      ? 'text-background-type-poison'
      : mainType === 'psychic'
      ? 'text-background-type-psychic'
      : mainType === 'steel'
      ? 'text-background-type-steel'
      : mainType === 'water'
      ? 'text-background-type-water'
      : mainType === 'electric'
      ? 'text-background-type-electric'
      : mainType === 'flying'
      ? 'text-background-type-flying'
      : mainType === 'ice'
      ? 'text-background-type-ice'
      : 'text-background-type-rock';

  return style;
};

export const ColorGradientTernary = (mainType: string) => {
  const style =
    mainType === 'grass'
      ? 'from-[#8bbe8a] dark:from-[#2a6233]'
      : mainType === 'dark'
      ? 'from-[#6f6e78] dark:from-[#23222A]'
      : mainType === 'dragon'
      ? 'from-[#7383b9] dark:from-[#36426C]'
      : mainType === 'fairy'
      ? 'from-[#eba8c3] dark:from-[#945469]'
      : mainType === 'fighting'
      ? 'from-[#eb4971] dark:from-[#85001F]'
      : mainType === 'fire'
      ? 'from-[#ffa756] dark:from-[#B15A16]'
      : mainType === 'ghost'
      ? 'from-[#8571be] dark:from-[#33245F]'
      : mainType === 'bug'
      ? 'from-[#6bd674] dark:from-[#2A8032]'
      : mainType === 'ground'
      ? 'from-[#f78551] dark:from-[#872C06]'
      : mainType === 'normal'
      ? 'from-[#b5b9c4] dark:from-[#61636E]'
      : mainType === 'poison'
      ? 'from-[#9f6397] dark:from-[#4D145A]'
      : mainType === 'psychic'
      ? 'from-[#ff6568] dark:from-[#A70D0F]'
      : mainType === 'steel'
      ? 'from-[#4c91b2] dark:from-[#073A52]'
      : mainType === 'water'
      ? 'from-[#58abf6] dark:from-[#155295]'
      : mainType === 'electric'
      ? 'from-[#d4ba79] dark:from-[#7F6A35]'
      : mainType === 'flying'
      ? 'from-[#83a2e3] dark:from-[#354E81]'
      : mainType === 'ice'
      ? 'from-[#91d8df] dark:from-[#427B81]'
      : 'from-[#d4c294] dark:from-[#7E6642]';
  return style;
};

export const textColorTernary = (mainType: string) => {
    const style = mainType === 'grass'
    ? 'text-type-grass dark:text-background-light-type-grass'
    : mainType === 'dark'
    ? 'text-type-dark dark:text-background-light-type-dark'
    : mainType === 'dragon'
    ? 'text-type-dragon dark:text-background-light-type-dragon'
    : mainType === 'fairy'
    ? 'text-type-fairy dark:text-background-light-type-fairy'
    : mainType === 'fighting'
    ? 'text-type-fighting dark:text-background-light-type-fighting'
    : mainType === 'fire'
    ? 'text-type-fire dark:text-background-light-type-fire'
    : mainType === 'ghost'
    ? 'text-type-ghost dark:text-background-light-type-ghost'
    : mainType === 'bug'
    ? 'text-type-bug dark:text-background-light-type-bug'
    : mainType === 'ground'
    ? 'text-type-ground dark:text-background-light-type-ground'
    : mainType === 'normal'
    ? 'text-type-normal dark:text-background-light-type-normal'
    : mainType === 'poison'
    ? 'text-type-poison dark:text-background-light-type-poison'
    : mainType === 'psychic'
    ? 'text-type-psychic dark:text-background-light-type-psychic'
    : mainType === 'steel'
    ? 'text-type-steel dark:text-background-light-type-steel'
    : mainType === 'water'
    ? 'text-type-water dark:text-background-light-type-water'
    : mainType === 'electric'
    ? 'text-background-light-type-electric dark:text-background-light-type-electric'
    : mainType === 'flying'
    ? 'text-type-flying dark:text-background-light-type-flying'
    : mainType === 'ice'
    ? 'text-type-ice dark:text-background-light-type-ice'
    : 'text-type-rock dark:text-background-light-type-rock';
  return style;
}
